apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      volumes:
        - name: exam-storage
          persistentVolumeClaim:
            claimName: exam-pvc
      containers:
        - name: nodejs
          image: nguyendinhtoan/nodejs:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/var/lib/exam"
              name: exam-storage
      imagePullSecrets:
        - name: regcred


      